spring:
  profiles:
      active: dev
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  h2:
      console:
          enabled: true
  http:
    multipart:
       max-file-size: 128KB
       max-request-size: 128KB