server:
  port: 8007
  tomcat:
    uri-encoding: UTF-8
####设置mysql数据库源以及用户名密码，这里采用阿里的druid连接池####
spring:
      datasource:
         type: com.alibaba.druid.pool.DruidDataSource
         url: jdbc:mysql://192.168.1.69:8635/cloudmanager?characterEncoding=utf8&useSSL=false
         username: root
         password: dove1985
         driverClassName: com.mysql.jdbc.Driver
         initialSize: 5
         minIdle: 5
         maxActive: 20
         maxWait: 60000
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1 FROM DUAL
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
         maxPoolPreparedStatementPerConnectionSize: 20
         filters: stat,wall,log4j
         connectionProperties: druid.stat.mergeSql=true;druid.state.slowSqMills=5000
####JPA设置配置model自动创建和更新，即如果数据没有对应的表创建，结构不同则更新####
      jpa:
         hibernate:
           ddl-auto: update
#####设置日志######
logging:
   file: ..//logs//gateway.log
   level:
     root: info
####druid监控页面用户名，密码###
druid:
   loginUsername: admin
   loginPassword: admin123456